spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/skill?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
  mvc:
    view:
      suffix: .jsp
      prefix: /jsp/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: localhost
    database: 0
    timeout: 8000
    port: 6379
mybatis:
  type-aliases-package: com.example.com.springboot.mapper
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
